// <auto-generated />
namespace MovieReviewPassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoviePosterExtension : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoviePosterExtension));
        
        string IMigrationMetadata.Id
        {
            get { return "202106201540210_MoviePosterExtension"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
